name: test

on: [push]

jobs:
  test:
    # Где запускаем
    runs-on: ubuntu-latest
    # Что делаем
    steps:
      # Выкачиваем репозиторий
      - uses: actions/checkout@v3
      # Настраиваем java
      - uses: actions/setup-node@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      # Взяли с selenoid github actions
      - uses: Xotabu4/selenoid-github-action@v2
      # Запускаем тесты
      - run: ./gradlew clean test -Dselenide.remote=gttps://localhost:4444/wd/hub
      # Скачиваем историю тестов
      - uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      # Генерируем отчет
      - uses: simple-alf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-history
          allure_history: allure-history
      # Публикуем отчет
      - uses: peaceiris/actions-gh-pages@v2
        if: always()
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
