name: test

on: [push]

jobs:
  test:
    # Где запускаем
    runs-on: ubuntu-latest
    # Что делаем
    steps:
      # Выкачиваем репозиторий
      - uses: actions/checkout@v3
      # Настраиваем java
      - uses: actions/setup-node@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      # Взяли с selenoid github actions
      - uses: Xotabu4/selenoid-github-action@v2
      # Запускаем тесты
      - run: ./gradlew clean test -Dselenide.remote=gttps://localhost:4444/wd/hub

